// <auto-generated />
namespace UniTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Types_in_TPH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Types_in_TPH));
        
        string IMigrationMetadata.Id
        {
            get { return "201703040050528_Types_in_TPH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
