// <auto-generated />
namespace UniTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Name_in_ChatRoom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Name_in_ChatRoom));
        
        string IMigrationMetadata.Id
        {
            get { return "201703040006349_Name_in_ChatRoom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
