// <auto-generated />
namespace UniTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Images_to_File_And_Optional_Birthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Images_to_File_And_Optional_Birthday));
        
        string IMigrationMetadata.Id
        {
            get { return "201703050245292_Images_to_File_And_Optional_Birthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
