// <auto-generated />
namespace UniTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChatRoom_Participants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChatRoom_Participants));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141855102_ChatRoom_Participants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
