// <auto-generated />
namespace UniTime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Comment_And_Reply_Length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Comment_And_Reply_Length));
        
        string IMigrationMetadata.Id
        {
            get { return "201703251325082_Comment_And_Reply_Length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
